[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcap-data-loader"
version = "0.2.4"
description = "MCAP Data Loader"
authors = [{ name = "OpenGHz", email = "your.email@example.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pydantic",
    "pydantic-settings",
    "pydantic_yaml",
    "numpy",
    "more-itertools",
    "toolz",
    "cachetools",
    "typing-extensions",
    "flatbuffers",
    "foxglove-schemas-flatbuffer",
    "mcap",
    "pymcap",
    "av",
    "PyTurboJPEG",
    "natsort",
    "array-api-compat",
    # "types-array-api",
    "termcolor",
    "inflection",
    "send2trash >=1.8.3",
]
urls = { "repository" = "https://github.com/OpenGHz/MCAP-DataLoader.git" }

# Optional dependencies
[project.optional-dependencies]
letrain = ["hydra-core", "torchdata"]

[tool.setuptools.packages.find]
where = ["."]
include = ["mcap_data_loader*"]

[tool.setuptools.package-data]
# Include FlatBuffers schema files in the wheel/sdist
"mcap_data_loader" = ["schemas/**/*.fbs", "schemas/**/*.bfbs"]

[tool.setuptools]
include-package-data = true

[project.scripts]
mcap_lerobot_train = "mcap_data_loader.datasets.mcap_lerobot:train"
mcap_lerobot_infer = "mcap_data_loader.datasets.mcap_lerobot:infer"
