# automatically generated by the FlatBuffers compiler, do not modify

# namespace: airbot_fbs

class DataType(object):
    UNKNOWN = 0
    UINT8 = 1
    INT8 = 2
    UINT16 = 3
    INT16 = 4
    FLOAT32 = 5
    FLOAT64 = 6
