# automatically generated by the FlatBuffers compiler, do not modify

# namespace: airbot_fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageShape(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # ImageShape
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageShape
    def Dims(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.DimsLength())]
        elif j >= 0 and j < self.DimsLength():
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # ImageShape
    def DimsAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint32Flags, self._tab.Pos + 0, self.DimsLength())

    # ImageShape
    def DimsLength(self):
        return 3

    # ImageShape
    def DimsIsNone(self):
        return False


def CreateImageShape(builder, dims):
    builder.Prep(4, 12)
    for _idx0 in range(3 , 0, -1):
        builder.PrependUint32(dims[_idx0-1])
    return builder.Offset()
