# automatically generated by the FlatBuffers compiler, do not modify

# namespace: airbot_fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MultiChannelImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiChannelImage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiChannelImage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MultiChannelImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiChannelImage
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from airbot_fbs.ImageShape import ImageShape
            obj = ImageShape()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultiChannelImage
    def Dtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MultiChannelImage
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MultiChannelImage
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # MultiChannelImage
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultiChannelImage
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def MultiChannelImageStart(builder):
    builder.StartObject(3)

def Start(builder):
    MultiChannelImageStart(builder)

def MultiChannelImageAddShape(builder, shape):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)

def AddShape(builder, shape):
    MultiChannelImageAddShape(builder, shape)

def MultiChannelImageAddDtype(builder, dtype):
    builder.PrependInt8Slot(1, dtype, 0)

def AddDtype(builder, dtype):
    MultiChannelImageAddDtype(builder, dtype)

def MultiChannelImageAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    MultiChannelImageAddData(builder, data)

def MultiChannelImageStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return MultiChannelImageStartDataVector(builder, numElems)

def MultiChannelImageEnd(builder):
    return builder.EndObject()

def End(builder):
    return MultiChannelImageEnd(builder)
