# automatically generated by the FlatBuffers compiler, do not modify

# namespace: foxglove_schemas_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A collection of N-dimensional points, which may contain additional fields with information like normals, intensity, etc.
class PointCloud2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PointCloud2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPointCloud2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PointCloud2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Timestamp of point cloud
    # PointCloud2
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from foxglove_schemas_flatbuffer.Time import Time
            obj = Time()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame of reference
    # PointCloud2
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The origin of the point cloud relative to the frame of reference
    # PointCloud2
    def Pose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from foxglove_schemas_flatbuffer.Pose import Pose
            obj = Pose()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Number of bytes between points in the `data`
    # PointCloud2
    def PointStride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Fields in `data`.
    # PointCloud2
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from foxglove_schemas_flatbuffer.PackedElementField import PackedElementField
            obj = PackedElementField()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PointCloud2
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PointCloud2
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Point data, interpreted using `fields`
    # PointCloud2
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # PointCloud2
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # PointCloud2
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PointCloud2
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Number of bytes between rows in the `data`. If the point cloud is unordered, this should be set to `point_stride * num_points`.
    # PointCloud2
    def RowStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Whether the point data is big-endian. If false, the data is little-endian.
    # PointCloud2
    def IsBigendian(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Whether the point cloud is dense (i.e., all points are valid). If false, there may be invalid points in the data, which should be ignored when processing. This field is not used by foxglove_schemas_flatbuffer Studio, but may be useful for applications that need to distinguish between valid and invalid points.
    # PointCloud2
    def IsDense(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Height of the point cloud. For unordered point clouds, this should be set to 1.
    # PointCloud2
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Width of the point cloud. For unordered point clouds, this should be set to the number of points in the cloud. For ordered point clouds, this should be set to the width of the point cloud, and `height` should be set to the height of the point cloud.
    # PointCloud2
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PointCloud2Start(builder):
    builder.StartObject(11)

def Start(builder):
    PointCloud2Start(builder)

def PointCloud2AddTimestamp(builder, timestamp):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    PointCloud2AddTimestamp(builder, timestamp)

def PointCloud2AddFrameId(builder, frameId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(frameId), 0)

def AddFrameId(builder, frameId):
    PointCloud2AddFrameId(builder, frameId)

def PointCloud2AddPose(builder, pose):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pose), 0)

def AddPose(builder, pose):
    PointCloud2AddPose(builder, pose)

def PointCloud2AddPointStride(builder, pointStride):
    builder.PrependUint32Slot(3, pointStride, 0)

def AddPointStride(builder, pointStride):
    PointCloud2AddPointStride(builder, pointStride)

def PointCloud2AddFields(builder, fields):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)

def AddFields(builder, fields):
    PointCloud2AddFields(builder, fields)

def PointCloud2StartFieldsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFieldsVector(builder, numElems):
    return PointCloud2StartFieldsVector(builder, numElems)

def PointCloud2AddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    PointCloud2AddData(builder, data)

def PointCloud2StartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return PointCloud2StartDataVector(builder, numElems)

def PointCloud2AddRowStep(builder, rowStep):
    builder.PrependUint32Slot(6, rowStep, 0)

def AddRowStep(builder, rowStep):
    PointCloud2AddRowStep(builder, rowStep)

def PointCloud2AddIsBigendian(builder, isBigendian):
    builder.PrependBoolSlot(7, isBigendian, 0)

def AddIsBigendian(builder, isBigendian):
    PointCloud2AddIsBigendian(builder, isBigendian)

def PointCloud2AddIsDense(builder, isDense):
    builder.PrependBoolSlot(8, isDense, 0)

def AddIsDense(builder, isDense):
    PointCloud2AddIsDense(builder, isDense)

def PointCloud2AddHeight(builder, height):
    builder.PrependUint32Slot(9, height, 0)

def AddHeight(builder, height):
    PointCloud2AddHeight(builder, height)

def PointCloud2AddWidth(builder, width):
    builder.PrependUint32Slot(10, width, 0)

def AddWidth(builder, width):
    PointCloud2AddWidth(builder, width)

def PointCloud2End(builder):
    return builder.EndObject()

def End(builder):
    return PointCloud2End(builder)
